
DROP SCHEMA IF EXISTS Makeleles ;
/*Creación del schema*/
CREATE SCHEMA IF NOT EXISTS Makeleles;
USE Makeleles;

/*Drop tables de todas las tablas*/
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS CENTRO;
DROP TABLE IF EXISTS CURSO;
DROP TABLE IF EXISTS ALUMNO;
DROP TABLE IF EXISTS EQUIPO;
DROP TABLE IF EXISTS PREGUNTA;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS PROFESOR;
DROP TABLE IF EXISTS pertenece;
DROP TABLE IF EXISTS CATEGORIA ;
DROP TABLE IF EXISTS RESPUESTA ;
DROP TABLE IF EXISTS responde ;

CREATE TABLE IF NOT EXISTS USUARIO(
	DNI VARCHAR(11) NOT NULL,
	Nombre VARCHAR(20) NOT NULL,
	Clave VARCHAR(20) NOT NULL,
	FechaNacimiento DATE NOT NULL,
	PRIMARY KEY (DNI));


CREATE TABLE IF NOT EXISTS CENTRO(
	idCentro INT NOT NULL,
	Nombre VARCHAR(20) NOT NULL,
	Direccion VARCHAR(40) NOT NULL,
	PRIMARY KEY (idCentro));


CREATE TABLE IF NOT EXISTS CURSO(
	idCurso VARCHAR(10) NOT NULL,
	Nombre VARCHAR(20) NOT NULL,
	CENTRO_idCentro INT NOT NULL,
	PRIMARY KEY (idCurso, CENTRO_idCentro),
  CONSTRAINT fk_CURSO_CENTRO1 FOREIGN KEY (CENTRO_idCentro) REFERENCES CENTRO(idCentro) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS ALUMNO (
  USUARIO_DNI VARCHAR(11) NOT NULL,
  PRIMARY KEY (USUARIO_DNI),
  CONSTRAINT fk_ALUMNO_USUARIO1 FOREIGN KEY (USUARIO_DNI) REFERENCES USUARIO (DNI) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS EQUIPO (
  idEquipo VARCHAR(10) NOT NULL,
  Nombre VARCHAR(20) NOT NULL,
  ALUMNO_USUARIO_DNI VARCHAR(11) NOT NULL,
  CURSO_idCurso VARCHAR(10) NOT NULL,
  CURSO_CENTRO_idCentro INT NOT NULL,
  PRIMARY KEY (idEquipo),
  CONSTRAINT fk_EQUIPO_ALUMNO1 FOREIGN KEY (ALUMNO_USUARIO_DNI) REFERENCES ALUMNO (USUARIO_DNI) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_EQUIPO_CURSO1 FOREIGN KEY (CURSO_idCurso, CURSO_CENTRO_idCentro) REFERENCES CURSO (idCurso , CENTRO_idCentro) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS PREGUNTA (
  idPregunta INT NOT NULL,
  Encunciado VARCHAR(200) NOT NULL,
  Definicion VARCHAR(150) NOT NULL,
  PRIMARY KEY (idPregunta));


CREATE TABLE IF NOT EXISTS PROFESOR (
  USUARIO_DNI VARCHAR(11) NOT NULL,
  Rol VARCHAR(20) NOT NULL,
  PRIMARY KEY (USUARIO_DNI),
  CONSTRAINT fk_PROFESOR_USUARIO1 FOREIGN KEY (USUARIO_DNI) REFERENCES USUARIO (DNI) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS pertenece (
  PROFESOR_USUARIO_DNI VARCHAR(11) NOT NULL,
  CURSO_idCurso VARCHAR(10) NOT NULL,
  CURSO_CENTRO_idCentro INT NOT NULL,
  PRIMARY KEY (PROFESOR_USUARIO_DNI, CURSO_idCurso, CURSO_CENTRO_idCentro),
  CONSTRAINT fk_PROFESOR_has_CURSO_PROFESOR1 FOREIGN KEY (PROFESOR_USUARIO_DNI) REFERENCES PROFESOR (USUARIO_DNI) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_pertenece_CURSO1 FOREIGN KEY (CURSO_idCurso , CURSO_CENTRO_idCentro) REFERENCES CURSO (idCurso , CENTRO_idCentro) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS CATEGORIA (
  idCategoria INT NOT NULL,
  Nombre VARCHAR(20) NOT NULL,
  Color VARCHAR(15) NOT NULL,
  PREGUNTA_idPregunta INT NOT NULL,
  PRIMARY KEY (idCategoria),
  CONSTRAINT fk_CATEGORIA_PREGUNTA1 FOREIGN KEY (PREGUNTA_idPregunta) REFERENCES PREGUNTA (idPregunta) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS RESPUESTA (
  Valor_Respuesta VARCHAR(20) NOT NULL,
  Peso VARCHAR(45) NOT NULL,
  PRIMARY KEY (Valor_Respuesta));


CREATE TABLE IF NOT EXISTS responde (
  PREGUNTA_idPregunta INT NOT NULL,
  ALUMNO_USUARIO_DNI VARCHAR(11) NOT NULL,
  RESPUESTA_Valor_Respuesta VARCHAR(20) NOT NULL,
  PRIMARY KEY (PREGUNTA_idPregunta, ALUMNO_USUARIO_DNI, RESPUESTA_Valor_Respuesta),
  CONSTRAINT fk_responde_PREGUNTA1 FOREIGN KEY (PREGUNTA_idPregunta) REFERENCES PREGUNTA (idPregunta) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_responde_ALUMNO1 FOREIGN KEY (ALUMNO_USUARIO_DNI) REFERENCES ALUMNO (USUARIO_DNI) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_responde_RESPUESTA1 FOREIGN KEY (RESPUESTA_Valor_Respuesta) REFERENCES RESPUESTA (Valor_Respuesta) ON DELETE CASCADE ON UPDATE CASCADE);




